name: Minecraft Forge Server with Serveo

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  start-server:
    runs-on: ubuntu-latest  # Usa un servidor virtual con Linux
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Forge 1.20.1 usa Java 17

      - name: Aceptar EULA
        run: echo "eula=true" > eula.txt

      - name: Iniciar el servidor Forge
        run: |
          chmod +x forge-1.20.1-xx.xx.xx.jar
          nohup java -Xmx2G -Xms2G -jar forge-1.20.1-xx.xx.xx.jar nogui &

      - name: Abrir túnel Serveo
        run: |
          nohup ssh -o StrictHostKeyChecking=no -R 25565:localhost:25565 serveo.net &
